apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-lesson-04
  namespace: my-postgres
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deployment-lesson-04
  template:
    metadata:
      labels:
        app: deployment-lesson-04
    spec:
      hostNetwork: true
      containers:
      - image: postgres:10.13
        name: postgresql
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP        
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          value: testdatabase
        - name: POSTGRES_USER
          value: testuser
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_PASSWORD          
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi              
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-pvc-hdd-5