apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc-hdd-5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-ceph-hdd-dp1
