apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geekbrains
spec:
  rules:
    - host: prod
      http:
        paths:
          - path: /users
            pathType: Exact
            backend:
              service:
                name: geekbrains
                port:
                  number: 8000
            